services:
  - type: web
    name: milk-billing
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py createsuperuser --noinput || true
      python manage.py collectstatic --noinput

    startCommand: gunicorn milkproject.wsgi:application

    envVars:
      - key: DJANGO_SUPERUSER_USERNAME
        value: kiruba_karan_123
      - key: DJANGO_SUPERUSER_PASSWORD
        value:kiruba
      - key: DJANGO_SUPERUSER_EMAIL
        value: dhayalankiruba17@mail.com
      - key: DJANGO_SETTINGS_MODULE
        value: milkproject.settings
      - key: PYTHON_VERSION
        value: 3.10
